#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# Override Debian's default cyan/black and black/blue colour scheme
set color_normal=light-gray/black
set color_highlight=black/light-gray
set menu_color_normal=light-gray/black
set menu_color_highlight=black/light-gray
